FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy source code
COPY . .

# Run tests
CMD ["npm", "test", "--", "--coverage", "--testPathIgnorePatterns=.*/integration/.*", "--forceExit", "--detectOpenHandles"] 